= Spring Data REST npm module

This npm module isn't much. It's just a preconfigured way to talk to a Spring Data REST service via https://github.com/cujojs/rest[rest.js].

== What is Spring Data REST?

Please check out my slide show from SpringOne 2014, https://speakerdeck.com/gregturn/springone2gx-2014-spring-data-rest-data-meets-hypermedia[Spring Data REST: Data meets hypermedia]. It is a quick intro into what Spring Data REST offers.

== What does this module have?

To talk to Spring Data REST, you essentially need a client configured for HAL. rest.js provides this feature. It just takes a few extra steps to configure it.

You can either do a lot of reading, like I did, or simply use this module to get going right away.

=== Using `restInvoker`

For an example of making REST calls, look at this snippet inspired from the test cases:

[source,javascript]
----
var sdr = require('sdr');

sdr.restInvoker({method: 'GET', path: 'http://rest-app-in-five-minutes.cfapps.io/employees'})
	.done(function(response) {

		console.log(response.status.code); // should be 200
		console.log(response.headers['Content-Type']); // should be application/hal+json

		var employees = response.entity._embedded.employees;

		employees.forEach(function(employee) {
			console.log(employee);
		})

		// Should print out something like this:
		// {
		//		"firstName": "Bilbo",
		//		"lastName": "Baggins",
		//		"title": "thief",
		//		"_links": {
		//			"self": {
		//				"href": "<URI to this item>"
		//			}
		//		}
		// }
	})
----

Making REST calls using `restInvoker` returns an https://promisesaplus.com/[A+-compliant promise]. This sample shows
how to process the response.

Want to create something via `POST`?

[source,javascript]
----
sdr.restInvoker({
	method: 'POST',
	path: employeesUri,
	entity: {
		firstName: 'Frodo',
		lastName: 'Baggins',
		title: 'ring bearer'
	},
	headers: {'Content-Type': 'application/json'}
}).then(function(response) {

	console.log(response.status.code); // should be 201
	console.log(response.headers['Location']); // should contain URI for new resource

	return sdr.restInvoker({
		method: 'GET',
		path: response.headers['Location']
	});
}).done(function(employee) {

	console.log(employee.firstName); // should be Frodo
	console.log(employee.lastName); // should be Baggins
	console.log(employee.title); // should be ring bearer
});
----

See how this nice, promise-based API lets you chain together operations without getting mired in ugly callbacks?

=== Using `follow` to get out URIs and into semantic relationships

`restInvoker` is real handy for doing URI-based ops. You saw how to *GET* and *POST* quite smoothly. But is that
what we want to be doing when navigating hypermedia?

To navigate from a root URI through a chain of URIs, use this simple alternative:

[source,javascript]
----
require('should');

var sdr = require('sdr');

// Start with rootUri -then-> rel: "employees" -then-> collection "employees"
sdr.follow('http://rest-app-in-five-minutes.cfapps.io', ['employees', 'employees'])
	.done(function(employees) {

		employees.forEach(function(employee) {
			console.log(employee);
		})

		// Should print out something like this:
		// {
		//		"firstName": "Bilbo",
		//		"lastName": "Baggins",
		//		"title": "thief",
		//		"_links": {
		//			"self": {
		//				"href": "<URI to this item>"
		//			}
		//		}
		// }
	})
----

What's the difference in using `follow` vs. `restInvoker`? `follow` shortcuts the process of navigating through a
collection of hypermedia relationships. It moves your attention to the semantic relationship between URIs. The first
example where you saw `restInvoker` showed only one `GET`. To start at the root URI and hop along a chain would require
repeating that process over and over.

This comes in handy when you start to navigate different relationships. The example above started with the root URI.
But a more realistic example would be customers and their orders. For example, if you emailed a customer about an order,
it would be very easy to include a link to that order's resource.

* http://example.com/orders/58

Using this nugget of knowledge, if the customer visits the order, it becomes possible to provide links back to ALL
their orders by using:

[source,javascript]
----
sdr.follow('http://example.com/orders/58', ['customer', 'orders'])
	.then(function(orders) {
		// do something the array of orders
	});
----

From a given order, you can navigate to the related customer, and then to that customer's orders. The focus with
hypermedia becomes the semantic relationships between URIs, not the URIs themselves.

Frankly, THIS is the type of code I prefer writing when talking to HAL-based backends. It sets things up for nice usage
of https://github.com/cujojs/when[when.js] when writing async operations.
